// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/health": {
            "get": {
                "tags": ["Health"],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/api/v1/auth/register": {
            "post": {
                "tags": ["Auth"],
                "summary": "Register a new user",
                "parameters": [{
                    "in": "body",
                    "name": "body",
                    "required": true,
                    "schema": {
                        "type": "object"
                    }
                }],
                "responses": {
                    "200": {"description": "OK"}
                }
            }
        },
        "/api/v1/auth/login": {
            "post": {
                "tags": ["Auth"],
                "summary": "User login",
                "parameters": [{
                    "in": "body",
                    "name": "body",
                    "required": true,
                    "schema": {
                        "type": "object"
                    }
                }],
                "responses": {
                    "200": {"description": "OK"}
                }
            }
        },
        "/api/v1/auth/profile": {
            "get": {
                "tags": ["Auth"],
                "summary": "Get current user profile",
                "security": [{"Bearer": []}],
                "responses": {
                    "200": {"description": "OK"}
                }
            }
        },
        "/api/v1/auth/logout": {
            "post": {
                "tags": ["Auth"],
                "summary": "Logout (revoke token)",
                "security": [{"Bearer": []}],
                "responses": {
                    "200": {"description": "OK"}
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Title:            "FullStack Engineering Lab API",
	Description:      "API documentation for FullStack Engineering Lab",
	Schemes:          []string{"http", "https"},
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
